"""
p05_jser_dc.py
====================
Replaces scalar-ASR JSER formula with per-sample computation, and adds
decision-change rate metrics (P0-A and P0-B corrections).

For each seed x lambda_r configuration, computes:

  ordinary_asr      : fraction of triggered samples clf predicts as target
  dc_rate           : fraction where clean source was NOT already target
  tpr_all           : detection rate over all triggered samples (old formula)
  jser_approx       : asr_json x (1 - tpr_all)            <- old (P05 formula)
  jser_persample    : mean(u_a & evades)                   <- P0-A corrected
  jser_dc           : mean(u_dc & evades)                  <- P0-B Prop-1 aligned
  dc_tpr            : TPR restricted to decision-changing successes
  already_target    : fraction of source samples already predicted as target
                      under clean inputs (outside Proposition-1 scope)

Uses identical R/C/E split as p05_indep_calibration_split.py.

Outputs (when external data are available):
  results/core_adaptive_comparison/indep_cal_mnist_jser_dc_metrics.csv
  results/core_adaptive_comparison/indep_cal_bloodmnist_jser_dc_metrics.csv

NOTE: this script requires external training data (model weights, raw dataset
samples) generated by training/scb_*_baseline.py and training/train_adaptive_qnn_fast.py.
Pre-computed results are available in the Zenodo deposit:
  https://doi.org/10.5281/zenodo.20700154

Theoretical context:
  jser_dc is the Tier-3 (empirical) realisation of Proposition 1's guarantee:
  it measures the fraction of genuine decision-change instances that both
  achieve attack success and evade detection -- precisely the event class for
  which D_Sigma > 0 is structurally guaranteed by {Z_k} subset S.
  The operational jser_persample additionally includes samples already
  predicted as the target class under clean inputs (already_target fraction).
"""

import sys, json, csv
from pathlib import Path
import numpy as np
from sklearn.covariance import LedoitWolf
from sklearn.metrics import roc_auc_score
import torch

ROOT = Path(__file__).resolve().parents[1]   # repo root

# ── data availability guard ───────────────────────────────────────────────────
if not (ROOT / 'results').exists():
    print('=' * 68)
    print('This script requires external training data (model weights, raw')
    print('dataset samples) generated by training/scb_*_baseline.py and')
    print('training/train_adaptive_qnn_fast.py.')
    print()
    print('Pre-computed results are available in the Zenodo deposit:')
    print('  https://doi.org/10.5281/zenodo.20700154')
    print()
    print('To verify key manuscript numbers from Zenodo CSVs, run:')
    print('    python reproduce_key_numbers.py')
    print('=' * 68)
    sys.exit(0)
# ─────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, str(Path(__file__).resolve().parent))   # for fast_circuit
from fast_circuit import _make_evals

OUT_DIR = ROOT / "results" / "core_adaptive_comparison"

# ── split sizes (must match p05_indep_calibration_split.py) ──────────────────
R_SIZE     = 300
C_SIZE     = 120
E_SIZE     = 120
SPLIT_SEED = 0

# ── gate helpers ──────────────────────────────────────────────────────────────
_H_gate  = np.array([[1, 1],[1,-1]], dtype=np.complex128) / np.sqrt(2)
_HS_gate = np.array([[1,-1j],[1,1j]], dtype=np.complex128) / np.sqrt(2)

def _apply_1q(psi, gate, q):
    dim    = psi.shape[1]
    step   = dim >> (q + 1)
    groups = dim // (2 * step)
    return np.einsum("ij,bkjl->bkil", gate,
                     psi.reshape(-1, groups, 2, step),
                     optimize=True).reshape(-1, dim)

def get_xyz_feats(samples, weights, n_layers, n_qubits):
    """Returns [X|Y|Z] concatenated, shape (N, 3*n_qubits)."""
    try:
        z_ev, _, _ = _make_evals(n_qubits)
    except Exception:
        z_ev = np.zeros((n_qubits, 2**n_qubits))
        for q in range(n_qubits):
            for s in range(2**n_qubits):
                bit = (s >> (n_qubits - 1 - q)) & 1
                z_ev[q, s] = 1.0 - 2.0 * bit
    norms = np.linalg.norm(samples, axis=1, keepdims=True).clip(min=1e-12)
    psi   = (samples / norms).astype(np.complex128)
    wr    = weights.reshape(n_layers, n_qubits, 2)
    for l in range(n_layers):
        for q in range(n_qubits):
            ct, st = np.cos(wr[l, q, 0]/2), np.sin(wr[l, q, 0]/2)
            psi = _apply_1q(psi, np.array([[ct,-st],[st,ct]], dtype=np.complex128), q)
            ep  = np.exp(1j * wr[l, q, 1]/2)
            psi = _apply_1q(psi, np.array([[1/ep,0],[0,ep]], dtype=np.complex128), q)
        for q in range(n_qubits):
            dim    = psi.shape[1]
            n      = int(np.log2(dim))
            cb, tb = n-1-q, n-1-((q+1) % n_qubits)
            states = np.arange(dim, dtype=np.int64)
            psi    = psi[:, np.where((states >> cb) & 1, states ^ (1 << tb), states)]
    probs = np.abs(psi)**2
    Z = (probs @ z_ev.T).astype(np.float64)
    X = np.stack([(np.abs(_apply_1q(psi, _H_gate,  q))**2 @ z_ev[q])
                  for q in range(n_qubits)], axis=1)
    Y = np.stack([(np.abs(_apply_1q(psi, _HS_gate, q))**2 @ z_ev[q])
                  for q in range(n_qubits)], axis=1)
    return np.hstack([X, Y, Z]).astype(np.float64)

def get_z_feats(samples, weights, n_layers, n_qubits):
    """Returns only Z features, shape (N, n_qubits). Z is last n_qubits cols of XYZ."""
    xyz = get_xyz_feats(samples, weights, n_layers, n_qubits)
    return xyz[:, 2*n_qubits:]

# ── fixed two-layer MLP classifier (frozen head) ─────────────────────────────
class FixedClassifier:
    def __init__(self, w0, b0, w3, b3):
        self.w0, self.b0, self.w3, self.b3 = w0, b0, w3, b3

    def forward(self, z):
        h = np.maximum(0, z @ self.w0.T + self.b0)
        return h @ self.w3.T + self.b3

def load_clf(model_path: Path) -> FixedClassifier:
    state = torch.load(model_path, map_location="cpu", weights_only=False)
    return FixedClassifier(
        w0=state["classifier.0.weight"].numpy(),
        b0=state["classifier.0.bias"].numpy(),
        w3=state["classifier.3.weight"].numpy(),
        b3=state["classifier.3.bias"].numpy(),
    )

# ── Mahalanobis squared distance helper ──────────────────────────────────────
def mahal_sq(xyz, mu, prec):
    d = xyz - mu
    return np.einsum("ni,ij,nj->n", d, prec, d)

# ── core evaluation ───────────────────────────────────────────────────────────
def evaluate_v2(adap_weights, clf, x_clean_target, x_poison_triggered,
                x_source_clean, n_layers, n_qubits, target_class, asr_json):
    """
    adap_weights       : adaptive QNN weights (1-D numpy array)
    clf                : FixedClassifier loaded from baseline model
    x_clean_target     : [540, D] clean target-class samples for detector calibration
    x_poison_triggered : [60, D] triggered source samples
    x_source_clean     : [60, D] the same 60 source samples WITHOUT trigger
    n_layers, n_qubits : circuit parameters
    target_class       : integer (binary clf: class 1 = attack target)
    asr_json           : scalar ASR from JSON (for old-formula comparison)
    """
    assert len(x_clean_target) == R_SIZE + C_SIZE + E_SIZE

    # Independent calibration split (identical seed and sizes as p05)
    rng = np.random.default_rng(SPLIT_SEED)
    idx = rng.permutation(len(x_clean_target))
    x_r = x_clean_target[idx[:R_SIZE]]
    x_c = x_clean_target[idx[R_SIZE:R_SIZE+C_SIZE]]
    x_e = x_clean_target[idx[R_SIZE+C_SIZE:]]

    xyz_r = get_xyz_feats(x_r.astype(np.float64), adap_weights, n_layers, n_qubits)
    xyz_c = get_xyz_feats(x_c.astype(np.float64), adap_weights, n_layers, n_qubits)
    xyz_e = get_xyz_feats(x_e.astype(np.float64), adap_weights, n_layers, n_qubits)
    xyz_p = get_xyz_feats(x_poison_triggered.astype(np.float64), adap_weights, n_layers, n_qubits)

    lw   = LedoitWolf().fit(xyz_r)
    mu   = lw.location_
    prec = lw.get_precision()

    sc = mahal_sq(xyz_c, mu, prec)
    se = mahal_sq(xyz_e, mu, prec)
    sp = mahal_sq(xyz_p, mu, prec)

    tau     = float(np.percentile(sc, 95))
    evades  = sp <= tau                      # per-sample: NOT detected
    tpr_all = float(np.mean(sp > tau))       # TPR over all triggered samples
    fpr_e   = float(np.mean(se > tau))

    # AUC (threshold-free)
    y_all     = np.concatenate([np.zeros(len(xyz_e)), np.ones(len(xyz_p))])
    s_all     = np.concatenate([se, sp])
    auc_indep = float(roc_auc_score(y_all, s_all))
    xyz_all   = np.vstack([xyz_r, xyz_c, xyz_e])
    s_a2      = np.concatenate([mahal_sq(xyz_all, mu, prec), sp])
    y_a2      = np.concatenate([np.zeros(len(xyz_all)), np.ones(len(sp))])
    auc_all   = float(roc_auc_score(y_a2, s_a2))
    mahal_d   = float(np.sqrt(sp).mean())

    # P0-A: per-sample attack success (using adaptive weights + frozen classifier)
    z_p             = get_z_feats(x_poison_triggered.astype(np.float64), adap_weights, n_layers, n_qubits)
    preds_triggered = np.argmax(clf.forward(z_p), axis=1)
    u_a             = (preds_triggered == target_class)
    ordinary_asr    = float(np.mean(u_a))
    jser_persample  = float(np.mean(u_a & evades))          # P0-A corrected JSER
    jser_approx     = float(asr_json * (1 - tpr_all)) if asr_json is not None else None

    # P0-B: decision-change restricted metrics (Proposition-1 scope)
    z_src       = get_z_feats(x_source_clean.astype(np.float64), adap_weights, n_layers, n_qubits)
    preds_clean = np.argmax(clf.forward(z_src), axis=1)

    # u_dc: triggered -> target AND clean -> NOT target (genuine decision change)
    u_dc           = u_a & (preds_clean != target_class)
    dc_rate        = float(np.mean(u_dc))
    jser_dc        = float(np.mean(u_dc & evades))           # P0-B Prop-1 aligned JSER
    already_target = float(np.mean(preds_clean == target_class))
    dc_tpr         = float(np.mean(sp[u_dc] > tau)) if u_dc.sum() > 0 else float('nan')

    return dict(
        auc_indep      = round(auc_indep, 4),
        auc_all        = round(auc_all, 4),
        asr_json       = round(asr_json, 4) if asr_json is not None else None,
        ordinary_asr   = round(ordinary_asr, 4),
        dc_rate        = round(dc_rate, 4),
        already_target = round(already_target, 4),
        tpr_all        = round(tpr_all, 4),
        fpr_e          = round(fpr_e, 4),
        jser_approx    = round(jser_approx, 4) if jser_approx is not None else None,
        jser_persample = round(jser_persample, 4),
        jser_dc        = round(jser_dc, 4),
        dc_tpr         = round(dc_tpr, 4) if not np.isnan(dc_tpr) else None,
        mahal_d        = round(mahal_d, 4),
        tau            = round(tau, 4),
    )

# ── dataset configurations ────────────────────────────────────────────────────
DATASETS = {
    "mnist": dict(
        data_dir     = ROOT / "data/Mnist/detail_single_samle",
        wgt_dir      = ROOT / "results/training_time/new_version",
        res_dir      = ROOT / "results/training_time/new_version",
        n_qubits     = 5,
        n_layers     = 12,
        pair         = "t7_vs_t0",
        pr           = "0.1",
        target_class = 1,
        seeds        = [42, 43, 44, 45, 46],
        lambdas      = [0.0, 0.5, 1.0, 2.0],
        out_csv      = OUT_DIR / "indep_cal_mnist_jser_dc_metrics.csv",
    ),
    "bloodmnist": dict(
        data_dir     = ROOT / "data/MedMnist/single_detect_20260411/epsilon_0.8",
        wgt_dir      = ROOT / "results/training_time_bloodmnist",
        res_dir      = ROOT / "results/training_time_bloodmnist",
        n_qubits     = 8,
        n_layers     = 8,
        pair         = "t6_vs_t0",
        pr           = "0.1",
        target_class = 1,
        seeds        = [42, 43, 44, 45, 46],
        lambdas      = [0.0, 0.5, 1.0, 2.0],
        out_csv      = OUT_DIR / "indep_cal_bloodmnist_jser_dc_metrics.csv",
    ),
}

FIELDNAMES = [
    "seed", "lambda_r", "epoch",
    "auc_indep", "auc_all",
    "asr_json", "ordinary_asr", "dc_rate", "already_target",
    "tpr_all", "fpr_e",
    "jser_approx", "jser_persample", "jser_dc", "dc_tpr",
    "mahal_d", "tau",
]

def run_dataset(name, cfg):
    print(f"\n{'='*78}")
    print(f"Dataset: {name.upper()}  (n={cfg['n_qubits']}q, L={cfg['n_layers']})")
    print(f"{'='*78}")
    hdr  = f"{'seed':>5}  {'lam':>5}  {'asr_j':>7}  {'ord_asr':>8}  "
    hdr += f"{'dc_rate':>8}  {'alrdy_t':>8}  {'jser_ap':>8}  {'jser_ps':>8}  {'jser_dc':>8}"
    print(hdr)
    print("-" * 80)

    rows = []
    with open(cfg["out_csv"], "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        writer.writeheader()

        for lam in cfg["lambdas"]:
            for seed in cfg["seeds"]:
                pr_s       = f"{float(cfg['pr']):.12g}"
                wgt        = cfg["wgt_dir"] / f"weights_seed={seed}_L{cfg['n_layers']}_lr{lam}.npy"
                res        = cfg["res_dir"] / f"result_seed={seed}_L{cfg['n_layers']}_lr{lam}.json"
                base       = (cfg["data_dir"] / f"seed_{seed}"
                              / f"layer_{cfg['n_layers']}_grid"
                              / cfg["pair"] / f"pr_{pr_s}")
                meta_path  = base / f"poisoned_samples_meta_seed_{seed}_pr_{pr_s}.pt"
                model_path = base / "models" / f"clean_model_seed_{seed}_epoch_200.pt"
                if not model_path.exists():
                    model_path = base / "models" / "clean_model_seed_200.pt"

                missing = [p for p in [wgt, meta_path, model_path] if not p.exists()]
                if missing:
                    print(f"  SKIP (missing): {missing[0].name}")
                    continue

                adap_weights = np.load(wgt).astype(np.float64)
                meta         = torch.load(meta_path, map_location="cpu", weights_only=False)
                clf          = load_clf(model_path)

                x_ct        = meta["target_clean_data"].numpy().astype(np.float32)
                x_p         = meta["poisoned_non_target_data"].numpy().astype(np.float32)
                idx_src     = meta["poison_indices_in_non_target"].numpy()
                x_src_clean = meta["non_target_clean_data"][idx_src].numpy().astype(np.float32)

                if len(x_ct) != R_SIZE + C_SIZE + E_SIZE:
                    print(f"  WARNING: expected 540 clean, got {len(x_ct)} -- skip")
                    continue

                asr_json, ep = 1.0, 0
                if res.exists():
                    r        = json.load(open(res))
                    fin      = r.get("final", r.get("latest", {}))
                    asr_json = fin.get("asr", 1.0)
                    ep       = fin.get("epoch", 0)

                m   = evaluate_v2(adap_weights, clf, x_ct, x_p, x_src_clean,
                                  cfg["n_layers"], cfg["n_qubits"],
                                  cfg["target_class"], asr_json)
                row = dict(seed=seed, lambda_r=lam, epoch=ep, **m)
                writer.writerow(row)
                rows.append(row)
                print(f"  {seed:>5}  {lam:>5}  {m['asr_json']:>7.4f}  "
                      f"{m['ordinary_asr']:>8.4f}  {m['dc_rate']:>8.4f}  "
                      f"{m['already_target']:>8.4f}  {m['jser_approx']:>8.4f}  "
                      f"{m['jser_persample']:>8.4f}  {m['jser_dc']:>8.4f}")

    lam1 = [r for r in rows if r["lambda_r"] == 1.0]
    if lam1:
        print(f"\n--- lambda_r=1 summary (n={len(lam1)} seeds) ---")
        for key in ["jser_approx", "jser_persample", "jser_dc",
                    "dc_rate", "already_target", "ordinary_asr"]:
            vals = [r[key] for r in lam1 if r[key] is not None]
            if vals:
                print(f"  {key:20s}: mean={np.mean(vals):.4f}  "
                      f"pop_sd={np.std(vals):.4f}  "
                      f"vals={[round(v, 4) for v in vals]}")
    print(f"\nSaved -> {cfg['out_csv']}")
    return rows

if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    for name, cfg in DATASETS.items():
        run_dataset(name, cfg)
    print("\nDone.")


